"""Add expiry_date to inventory_batch

Revision ID: 096fee98adb0
Revises: 58f3f7841b93
Create Date: 2026-08-05 17:49:49.028978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096fee98adb0'
down_revision = '58f3f7841b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_return_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('inventory_batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batch.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['purchase_return.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_return_item')
    op.drop_table('purchase_return')
    # ### end Alembic commands ###
