"""Add shop maintenance and block fields

Revision ID: 223e500b44a5
Revises: 558a7be117be
Create Date: 2026-08-07 17:12:34.924550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223e500b44a5'
down_revision = '558a7be117be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_return', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sale_return_item', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_return_item', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sale_return', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
