"""add discount and tax to sale

Revision ID: 2bba90aca6f0
Revises: f1edecd903e6
Create Date: 2026-07-24 15:48:23.810037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bba90aca6f0'
down_revision = 'f1edecd903e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('tax')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
