"""Add shop_id to sale_return and sale_return_item

Revision ID: 558a7be117be
Revises: bc603b995fd0
Create Date: 2026-08-07 15:06:01.188625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '558a7be117be'
down_revision = 'bc603b995fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('customer_transaction', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('purchase_return', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('purchase_return_item', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sale_return', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shop', ['shop_id'], ['id'])

    with op.batch_alter_table('sale_return_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shop', ['shop_id'], ['id'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sale_return_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('sale_return', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shop_id')

    with op.batch_alter_table('sale_item', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('purchase_return_item', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('purchase_return', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customer_transaction', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###