"""Add expiry_date to product

Revision ID: 58f3f7841b93
Revises: 879fe386a6c3
Create Date: 2026-08-05 15:37:14.479427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f3f7841b93'
down_revision = '879fe386a6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')

    # ### end Alembic commands ###
