"""Add shop maintenance and block fields

Revision ID: 5f359ad59e4c
Revises: 223e500b44a5
Create Date: 2026-08-07 17:15:22.199232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f359ad59e4c'
down_revision = '223e500b44a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_maintenance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('block_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('blocked_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blocked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['blocked_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('blocked_at')
        batch_op.drop_column('blocked_by')
        batch_op.drop_column('block_reason')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('is_maintenance')

    # ### end Alembic commands ###
