"""Add selling_price to inventory_batch

Revision ID: f1edecd903e6
Revises: 779c54dfa011
Create Date: 2026-07-23 23:49:26.086338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1edecd903e6'
down_revision = '779c54dfa011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_batch', schema=None) as batch_op:
        batch_op.drop_column('selling_price')

    # ### end Alembic commands ###
